# Generated by Django 6.0.4 on 2026-04-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('poblacion', models.IntegerField(default=0)),
                ('tiene_transporte_formal', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['municipio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('tipo_vehiculo', models.CharField(choices=[('combi', 'Combi'), ('camioneta', 'Camioneta Pick-up'), ('mototaxi', 'Mototaxi'), ('autobus', 'Autobus pequeno')], max_length=20)),
                ('capacidad', models.IntegerField(default=8)),
                ('placa', models.CharField(max_length=10)),
                ('ine_ultimos_4', models.CharField(max_length=4)),
                ('foto_vehiculo_url', models.URLField(blank=True)),
                ('calificacion', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_viajes', models.IntegerField(default=0)),
                ('verificado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('horarios', models.JSONField(default=list)),
                ('dias', models.JSONField(default=list)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='api.comunidad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='api.comunidad')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='api.transportista')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_texto', models.CharField(max_length=200)),
                ('destino_texto', models.CharField(max_length=200)),
                ('pasajeros', models.IntegerField(default=1)),
                ('telefono_whatsapp', models.CharField(max_length=20)),
                ('fecha_viaje', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='api.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='api.ruta')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitud')),
            ],
        ),
    ]
