# Generated by Django 6.0.4 on 2026-04-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportista',
            name='foto_vehiculo_url',
        ),
        migrations.AddField(
            model_name='transportista',
            name='foto_vehiculo_base64',
            field=models.TextField(blank=True, help_text='Imagen comprimida en Base64'),
        ),
    ]
