# Generated by Django 6.0.4 on 2026-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_transportista_foto_vehiculo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='nombre_nahuatl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='nombre_totonaco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
