# Generated by Django 6.0.4 on 2026-04-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comunidad_nombre_nahuatl_comunidad_nombre_totonaco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='telefono_whatsapp',
            field=models.CharField(max_length=30),
        ),
    ]
