# Generated by Django 6.0.4 on 2026-04-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_solicitud_telefono_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text='ID de WhatsApp o Teléfono', max_length=50, unique=True)),
                ('paso', models.CharField(choices=[('inicio', 'Inicio / Menú'), ('buscando_origen', 'Buscando Origen'), ('buscando_destino', 'Buscando Destino'), ('eligiendo_ruta', 'Eligiendo Ruta'), ('confirmando_fecha', 'Confirmando Fecha')], default='inicio', max_length=30)),
                ('origen_temp', models.CharField(blank=True, max_length=200, null=True)),
                ('destino_temp', models.CharField(blank=True, max_length=200, null=True)),
                ('ruta_id_temp', models.IntegerField(blank=True, null=True)),
                ('ultima_interaccion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
